### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by janasouza** [janasouza/marcando-de-batom#3]
# Coisas para fazer :)
- [x] Definir Layout.
- [x] Criar documentação.
- [x] Preparar assets. (Fonts, images, svgs, etc..)
- [x] Preparar estrutura básica do blog com Docpad.
- [x] Implementar CSS Layout.
- [ ] Implementar comportamento de SPA.
- [ ] Implementar infinity scroll.
- [x] Integração com redes sociais.
- [x] Automatizar inserção de conteúdo. (incluindo SEO especifico).
- [x] Passar Front-End Checklist.
- [x] Implementar Analytics de forma correta.
- [x] Automatizar Deploy.
